### ISSUE TITLE
Built Executable?

### ISSUE THREAD

**Issue by cole-st-john** [QualityInformationFramework/QIFRulesEditor#1]
Hello, I believe it was mentioned during the QIF Coffee Chat on DMSC Open Source Tools that built executables would be available on github, in particular for the QIF Rules Editor.  Is this still a possibility?  Thanks, Cole

**Comment by daniel-campbell** [comment]
Hi Cole, 
If you click here: 

![image](https://user-images.githubusercontent.com/10170984/162806858-11b8704f-0c6f-4277-be97-ae342fa96b2d.png)


...and then open the "Assets" box: 


![image](https://user-images.githubusercontent.com/10170984/162807333-a5af9983-70bf-4482-a12b-d40a1be88267.png)


You will see a ZIP file containing binaries. Let me know if this works okay.

**Comment by cole-st-john** [comment]
Thanks Daniel!
